name: Build y Push a Docker Hub

on:
  push:
    branches:
      - main  # o el branch que uses

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Clona el repo
      uses: actions/checkout@v3

    - name: Login a Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build de imagen Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/miapp:latest .

    - name: Push de imagen a Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/miapp:latest
